// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxpU-teX0Tq3oSb3JdQDpMa-lvUyO5Ztc',
    appId: '1:826325147634:web:c58e0c2108e78a0700956b',
    messagingSenderId: '826325147634',
    projectId: 'absensi-mahasiswa-61c0b',
    authDomain: 'absensi-mahasiswa-61c0b.firebaseapp.com',
    storageBucket: 'absensi-mahasiswa-61c0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSxsSJhRJIhjetYiLlMlFiuU-I2Mj_HWQ',
    appId: '1:826325147634:android:840f88313293a31e00956b',
    messagingSenderId: '826325147634',
    projectId: 'absensi-mahasiswa-61c0b',
    storageBucket: 'absensi-mahasiswa-61c0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzk_wcakBFV7hZRSnUYvERleGr5h0OykM',
    appId: '1:826325147634:ios:d75fa6399cdd951800956b',
    messagingSenderId: '826325147634',
    projectId: 'absensi-mahasiswa-61c0b',
    storageBucket: 'absensi-mahasiswa-61c0b.firebasestorage.app',
    iosBundleId: 'com.example.projectPab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzk_wcakBFV7hZRSnUYvERleGr5h0OykM',
    appId: '1:826325147634:ios:d75fa6399cdd951800956b',
    messagingSenderId: '826325147634',
    projectId: 'absensi-mahasiswa-61c0b',
    storageBucket: 'absensi-mahasiswa-61c0b.firebasestorage.app',
    iosBundleId: 'com.example.projectPab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxpU-teX0Tq3oSb3JdQDpMa-lvUyO5Ztc',
    appId: '1:826325147634:web:f56f4dda78bc0f0000956b',
    messagingSenderId: '826325147634',
    projectId: 'absensi-mahasiswa-61c0b',
    authDomain: 'absensi-mahasiswa-61c0b.firebaseapp.com',
    storageBucket: 'absensi-mahasiswa-61c0b.firebasestorage.app',
  );
}
